### ISSUE TITLE
✨FEAT. 식단 추천 페이지 구현

### ISSUE THREAD

**Issue by kmgnw** [2024-tantanmen/Frontend#27]
# 📝 Preview
식단 추천 페이지 구현

# ✅ Todo
- 선택 페이지
- [x] 헤더 구현
- [x] 탭바 구현
- [x] TextArea 구현
- [x] Choices 구현
- [x] 저장 버튼 구현

- 결과 페이지
- [x] 헤더 구현
- [x] 결과 메뉴 섹션 구현
- [x] 결과 메뉴 셀 구현
- [x] Choices 구현
- [x] 공유섹션/토스트 메시지 구현

# 📌 Remark
